"""empty message

Revision ID: 029c9f1c16a0
Revises: 6eb96d3c6918
Create Date: 2025-10-05 14:56:24.197153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029c9f1c16a0'
down_revision = '6eb96d3c6918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_chamber_applications_teacher_id_fkey'), type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('student_chamber_applications_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
