"""empty message

Revision ID: 08ccec5cf685
Revises: 4734de5e4a61
Create Date: 2026-05-27 08:39:33.191112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ccec5cf685'
down_revision = '4734de5e4a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification', sa.Enum('A', 'B', 'C', 'D', 'E', 'Z', 'N', name='classification_enum'), nullable=True))
        batch_op.add_column(sa.Column('classification_basis', sa.Enum('exam', 'request', 'performed_live', name='classification_basis_enum'), nullable=True))
        batch_op.add_column(sa.Column('classification_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject_enrollments', schema=None) as batch_op:
        batch_op.drop_column('classification_date')
        batch_op.drop_column('classification_basis')
        batch_op.drop_column('classification')

    # ### end Alembic commands ###
