"""empty message

Revision ID: 0b8e6c390369
Revises: 1acfc34f59e5
Create Date: 2025-09-06 08:11:01.337736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8e6c390369'
down_revision = '1acfc34f59e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firs_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('teachers_import_name_key'), type_='unique')
        batch_op.drop_column('import_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('import_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('teachers_import_name_key'), ['import_name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('full_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('firs_name')

    # ### end Alembic commands ###
