"""empty message

Revision ID: 10997825a7b4
Revises: fc81e51cf0d2
Create Date: 2025-09-28 13:10:57.035527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10997825a7b4'
down_revision = 'fc81e51cf0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_chamber_applications_ensemble_id_fkey'), type_='foreignkey')
        batch_op.drop_column('ensemble_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ensemble_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('student_chamber_applications_ensemble_id_fkey'), 'ensembles', ['ensemble_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
