"""empty message

Revision ID: 110431faee14
Revises: 285c33728f1c
Create Date: 2025-08-29 18:02:23.451081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110431faee14'
down_revision = '285c33728f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_semesters', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_ensemble_semester', ['ensemble_id', 'semester_id'])
        batch_op.drop_constraint(batch_op.f('ensemble_semesters_ensemble_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ensemble_semesters_semester_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ensembles', ['ensemble_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'semesters', ['semester_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semesters_academic_year_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semesters_academic_year_id'), ['academic_year_id'], unique=False)

    with op.batch_alter_table('ensemble_semesters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ensemble_semesters_semester_id_fkey'), 'semesters', ['semester_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ensemble_semesters_ensemble_id_fkey'), 'ensembles', ['ensemble_id'], ['id'])
        batch_op.drop_constraint('uq_ensemble_semester', type_='unique')

    # ### end Alembic commands ###
