"""empty message

Revision ID: 14268d1d40c7
Revises: 183358e601c1
Create Date: 2025-10-05 20:40:33.642030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14268d1d40c7'
down_revision = '183358e601c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
