"""empty message

Revision ID: 183358e601c1
Revises: 93f27fd79774
Create Date: 2025-10-05 20:26:05.595843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183358e601c1'
down_revision = '93f27fd79774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ensemble_applications_ensemble_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_ensemble_applications_ensemble_id'), ['ensemble_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ensemble_applications_ensemble_id'))
        batch_op.create_unique_constraint(batch_op.f('ensemble_applications_ensemble_id_key'), ['ensemble_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
