"""empty message

Revision ID: 1acfc34f59e5
Revises: 934576bccfed
Create Date: 2025-08-30 21:55:40.785698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acfc34f59e5'
down_revision = '934576bccfed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ensemble_instrumentation_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_ensemble_player'), type_='unique')
        batch_op.create_index(batch_op.f('ix_ensemble_players_ensemble_id'), ['ensemble_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ensemble_players_ensemble_instrumentation_id'), ['ensemble_instrumentation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ensemble_players_player_id'), ['player_id'], unique=False)
        batch_op.create_unique_constraint('uq_ensemble_player_once', ['player_id', 'ensemble_id'])
        batch_op.create_unique_constraint('uq_ensemble_player_per_part', ['player_id', 'ensemble_id', 'ensemble_instrumentation_id'])
        batch_op.create_foreign_key(None, 'ensemble_instrumentations', ['ensemble_instrumentation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('players_instrument_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'instruments', ['instrument_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('players_instrument_id_fkey'), 'instruments', ['instrument_id'], ['id'])

    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_ensemble_player_per_part', type_='unique')
        batch_op.drop_constraint('uq_ensemble_player_once', type_='unique')
        batch_op.drop_index(batch_op.f('ix_ensemble_players_player_id'))
        batch_op.drop_index(batch_op.f('ix_ensemble_players_ensemble_instrumentation_id'))
        batch_op.drop_index(batch_op.f('ix_ensemble_players_ensemble_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_ensemble_player'), ['player_id', 'ensemble_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('ensemble_instrumentation_id')

    # ### end Alembic commands ###
