"""empty message

Revision ID: 3288b325ca9c
Revises: aa8d750522f5
Create Date: 2025-09-17 21:24:49.419671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3288b325ca9c'
down_revision = 'aa8d750522f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ensemble_player_once'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_ensemble_player_per_part'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ensemble_player_per_part'), ['player_id', 'ensemble_id', 'ensemble_instrumentation_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_ensemble_player_once'), ['player_id', 'ensemble_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
