"""empty message

Revision ID: 4734de5e4a61
Revises: 7f101061dbb5
Create Date: 2026-02-02 17:14:11.775864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4734de5e4a61'
down_revision = '7f101061dbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_ens_instr_semester', ['ensemble_instrumentation_id', 'semester_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ens_instr_semester', type_='unique')

    # ### end Alembic commands ###
