"""empty message

Revision ID: 57ce4e491e24
Revises: 
Create Date: 2025-09-23 04:15:15.516930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ce4e491e24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ensemble_player_once'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_ensemble_player_per_part'), type_='unique')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('weight')

    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ensemble_player_per_part'), ['player_id', 'ensemble_id', 'ensemble_instrumentation_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('uq_ensemble_player_once'), ['player_id', 'ensemble_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
