"""empty message

Revision ID: 61e4b8bc9a5f
Revises: 69feecacdb40
Create Date: 2025-09-29 21:25:39.058709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e4b8bc9a5f'
down_revision = '69feecacdb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_application_exceptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_application_exceptions', schema=None) as batch_op:
        batch_op.drop_column('reviewer_comment')

    # ### end Alembic commands ###
