"""empty message

Revision ID: 622dd578fb12
Revises: 110431faee14
Create Date: 2025-08-29 23:09:09.270872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622dd578fb12'
down_revision = '110431faee14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_instrument')
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.create_index('ix_ay_start_end', ['start_date', 'end_date'], unique=False)

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.create_index('ix_semester_start_end', ['start_date', 'end_date'], unique=False)
        batch_op.create_unique_constraint('uq_semester_name_in_year', ['academic_year_id', 'name'])
        batch_op.drop_constraint(batch_op.f('fk_semesters_academic_year_id_academic_years'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'academic_years', ['academic_year_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_last_name'), ['last_name'], unique=False)
        batch_op.create_foreign_key(None, 'instruments', ['instrument_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_last_name'))
        batch_op.drop_index(batch_op.f('ix_students_active'))
        batch_op.drop_column('instrument_id')

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_semesters_academic_year_id_academic_years'), 'academic_years', ['academic_year_id'], ['id'])
        batch_op.drop_constraint('uq_semester_name_in_year', type_='unique')
        batch_op.drop_index('ix_semester_start_end')

    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_index('ix_ay_start_end')

    op.create_table('student_instrument',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('student_instrument_instrument_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_instrument_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_instrument_pkey'))
    )
    # ### end Alembic commands ###
