"""empty message

Revision ID: 645089ce9e2f
Revises: 307dae58138c
Create Date: 2025-09-06 12:28:32.068785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645089ce9e2f'
down_revision = '307dae58138c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_studia', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('id_studia')

    # ### end Alembic commands ###
