"""empty message

Revision ID: 645c05511d71
Revises: bee4cb389a2b
Create Date: 2025-10-08 14:28:48.998143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645c05511d71'
down_revision = 'bee4cb389a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
