"""empty message

Revision ID: 69feecacdb40
Revises: d776b8733571
Create Date: 2025-09-29 21:13:46.113114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69feecacdb40'
down_revision = 'd776b8733571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_application_exceptions', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_application_exceptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
