"""empty message

Revision ID: 6a43a24cee3f
Revises: 3288b325ca9c
Create Date: 2025-09-18 13:44:32.522674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a43a24cee3f'
down_revision = '3288b325ca9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_teachers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ensemble_teachers_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ensemble_teachers_teacher_id_fkey'), 'players', ['teacher_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
