"""empty message

Revision ID: 6eb96d3c6918
Revises: 7f1c48421f1b
Create Date: 2025-10-03 13:30:31.171207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb96d3c6918'
down_revision = '7f1c48421f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_application_exceptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_chamber_application_exceptions_teacher_id_fkey'), type_='foreignkey')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('student_chamber_application_exceptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('student_chamber_application_exceptions_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
