"""empty message

Revision ID: 7f101061dbb5
Revises: 645c05511d71
Create Date: 2026-02-02 16:48:37.539577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f101061dbb5'
down_revision = '645c05511d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ensemble_players_semester_id'), ['semester_id'], unique=False)
        batch_op.create_foreign_key(None, 'semesters', ['semester_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ensemble_players_semester_id'))
        batch_op.drop_column('semester_id')

    # ### end Alembic commands ###
