"""empty message

Revision ID: 82122548e6be
Revises: e41f1841a120
Create Date: 2025-09-30 10:46:31.279488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82122548e6be'
down_revision = 'e41f1841a120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_ensemble_teachers_semester_id'), ['semester_id'], unique=False)
        batch_op.create_foreign_key(None, 'semesters', ['semester_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ensemble_teachers_semester_id'))
        batch_op.drop_column('semester_id')

    # ### end Alembic commands ###
