"""empty message

Revision ID: 863858887a7d
Revises: c27b749f4b8f
Create Date: 2025-09-29 13:05:49.803554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863858887a7d'
down_revision = 'c27b749f4b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_application_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submission_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_application_players', schema=None) as batch_op:
        batch_op.drop_column('submission_date')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
