"""empty message

Revision ID: 934576bccfed
Revises: b5b7e3d1d691
Create Date: 2025-08-30 21:52:14.579628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934576bccfed'
down_revision = 'b5b7e3d1d691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_student_id'))
        batch_op.create_index(batch_op.f('ix_players_student_id'), ['student_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_student_id'))
        batch_op.create_index(batch_op.f('ix_players_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###
