"""empty message

Revision ID: 9792714a1011
Revises: 863858887a7d
Create Date: 2025-09-29 13:10:32.397903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9792714a1011'
down_revision = '863858887a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_application_players', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('submission_date')

    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submission_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.drop_column('submission_date')
        batch_op.drop_column('notes')

    with op.batch_alter_table('student_chamber_application_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
