"""Add hour donation to ensemble teacher

Revision ID: a77f31b5fd69
Revises: 6a43a24cee3f
Create Date: 2025-09-18 13:45:29.025516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77f31b5fd69'
down_revision = '6a43a24cee3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour_donation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_teachers', schema=None) as batch_op:
        batch_op.drop_column('hour_donation')

    # ### end Alembic commands ###
