"""EnsemblePlayer column player_id IS Nullable

Revision ID: aa8d750522f5
Revises: 
Create Date: 2025-09-17 11:45:53.880297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8d750522f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
