"""empty message

Revision ID: b5b7e3d1d691
Revises: 622dd578fb12
Create Date: 2025-08-30 21:50:50.868380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b7e3d1d691'
down_revision = '622dd578fb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_ensemble_player', ['player_id', 'ensemble_id'])
        batch_op.drop_constraint(batch_op.f('ensemble_players_ensemble_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ensemble_players_player_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'ensembles', ['ensemble_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_players_student_id'), ['student_id'], unique=False)
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_players_student_id'))
        batch_op.drop_column('student_id')

    with op.batch_alter_table('ensemble_players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ensemble_players_player_id_fkey'), 'players', ['player_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ensemble_players_ensemble_id_fkey'), 'ensembles', ['ensemble_id'], ['id'])
        batch_op.drop_constraint('uq_ensemble_player', type_='unique')

    # ### end Alembic commands ###
