"""add student and teacher FK to users

Revision ID: b6d5df76e27c
Revises: 08ccec5cf685
Create Date: 2026-06-15 15:56:35.745645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d5df76e27c'
down_revision = '08ccec5cf685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['student_id'])
        batch_op.create_unique_constraint(None, ['teacher_id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
