"""empty message

Revision ID: c27b749f4b8f
Revises: b54112a7277e
Create Date: 2025-09-29 10:01:40.383678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27b749f4b8f'
down_revision = 'b54112a7277e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erasmus', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subject_enrollments', schema=None) as batch_op:
        batch_op.drop_column('erasmus')

    # ### end Alembic commands ###
