"""empty message

Revision ID: cf9b9f088eea
Revises: 
Create Date: 2025-08-27 18:27:24.714287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9b9f088eea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
