"""empty message

Revision ID: d75cc96b62b1
Revises: 75e355465011
Create Date: 2025-09-29 15:18:44.197715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75cc96b62b1'
down_revision = '75e355465011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ensembles_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('ensembles_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
