"""empty message

Revision ID: d776b8733571
Revises: d75cc96b62b1
Create Date: 2025-09-29 18:40:46.020320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd776b8733571'
down_revision = 'd75cc96b62b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_chamber_applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('review_comment')

    # ### end Alembic commands ###
