"""empty message

Revision ID: e0fb15cb3bb9
Revises: 2bb7038b602b
Create Date: 2025-10-01 21:08:45.781537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fb15cb3bb9'
down_revision = '2bb7038b602b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exception_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'student_chamber_application_exceptions', ['exception_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensembles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exception_id')

    # ### end Alembic commands ###
