"""empty message

Revision ID: e41f1841a120
Revises: 4f08fb5fe46e
Create Date: 2025-09-30 09:54:48.719194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41f1841a120'
down_revision = '4f08fb5fe46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osobni_cislo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('osobni_cislo')

    # ### end Alembic commands ###
