"""empty message

Revision ID: e7a2d846b119
Revises: d9957eb15068
Create Date: 2025-09-06 08:31:27.923715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a2d846b119'
down_revision = 'd9957eb15068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=100)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
