"""empty message

Revision ID: e9df0051f0a5
Revises: 82122548e6be
Create Date: 2025-09-30 12:38:54.835507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9df0051f0a5'
down_revision = '82122548e6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_teachers', schema=None) as batch_op:
        batch_op.alter_column('hour_donation',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ensemble_teachers', schema=None) as batch_op:
        batch_op.alter_column('hour_donation',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
